;; Akira Baruah's emacs config

;; Keep track of load time
(defconst emacs-start-time (current-time))

;; Avoid garbage collection during init
(let ((gc-cons-threshold most-positive-fixnum))
(defun avoid-garbage-collection()
  (setq gc-cons-threshold most-positive-fixnum))
(defun reset-garbage-collection()
  (setq gc-cons-threshold 800000))
(add-hook 'minibuffer-setup-hook #'avoid-garbage-collection)
(add-hook 'minibuffer-exit-hook #'reset-garbage-collection)

;; TODO(https://debbugs.gnu.org/34341): Remove this workaround once fix lands.
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")

;; Package archives
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
;; Avoid calling (package-initialize) again after init. For explanation, see
;; https://www.reddit.com/r/emacs/comments/1rdstn/set_packageenableatstartup_to_nil_for_slightly/
(setq package-enable-at-startup nil)

;; Install use-package if needed
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Enable use-package
(eval-when-compile
  (require 'use-package))

;; Enable evil-mode
(use-package evil
  :ensure t
  :config
  (evil-mode))

;; Save backups to /tmp
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory t)))

;; Put custom autogenerated settings in a separate file
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file 'noerror))

;; Delete trailing whitespace on save
(add-hook 'before-save-hook 'delete-trailing-whitespace)

;; Message how long it took to load everything (minus packages)
(let ((elapsed (float-time (time-subtract (current-time)
                                          emacs-start-time))))
  (message "Loaded settings in %.3fs" elapsed))

)  ;; end gc-cons-threshold let
