name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [26.2, 26.3, snapshot]
    steps:
      - uses: purcell/setup-emacs@v1.0
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2.0.0
        with:
          path: .emacs.d

      - name: Run Emacs init
        run: emacs --script .emacs.d/init.el
        env:
          HOME: ${{ github.workspace }}
